-- MySQL Script generated by MySQL Workbench
-- Thu Nov  9 17:20:47 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bbclone
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bbclone
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bbclone` DEFAULT CHARACTER SET utf8 ;
USE `bbclone` ;

-- -----------------------------------------------------
-- Table `bbclone`.`Students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bbclone`.`Students` (
  `student_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NULL,
  `hash` VARCHAR(32) NULL,
  `email` VARCHAR(255) NULL,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  PRIMARY KEY (`student_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bbclone`.`Instructors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bbclone`.`Instructors` (
  `instructor_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NULL,
  `hash` VARCHAR(32) NULL,
  `email` VARCHAR(255) NULL,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  PRIMARY KEY (`instructor_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bbclone`.`Courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bbclone`.`Courses` (
  `course_id` INT NOT NULL AUTO_INCREMENT,
  `department` VARCHAR(255) NULL,
  `coursename` VARCHAR(255) NULL,
  `CRN` INT NULL,
  `semester` VARCHAR(6) NULL,
  `year` SMALLINT(4) NULL,
  PRIMARY KEY (`course_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bbclone`.`Enrollment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bbclone`.`Enrollment` (
  `student_id` INT NOT NULL,
  `course_id` INT NOT NULL,
  PRIMARY KEY (`student_id`, `course_id`),
  INDEX `course_id_idx` (`course_id` ASC),
  CONSTRAINT `student_id`
    FOREIGN KEY (`student_id`)
    REFERENCES `bbclone`.`Students` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `course_id`
    FOREIGN KEY (`course_id`)
    REFERENCES `bbclone`.`Courses` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bbclone`.`Instruction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bbclone`.`Instruction` (
  `instructor_id` INT NOT NULL,
  `course_id` INT NOT NULL,
  INDEX `instructor_id_idx` (`instructor_id` ASC),
  INDEX `course_id_idx` (`course_id` ASC),
  PRIMARY KEY (`instructor_id`, `course_id`),
  CONSTRAINT `instruction_instructor`
    FOREIGN KEY (`instructor_id`)
    REFERENCES `bbclone`.`Instructors` (`instructor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `instruction_course`
    FOREIGN KEY (`course_id`)
    REFERENCES `bbclone`.`Courses` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bbclone`.`Assignments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bbclone`.`Assignments` (
  `assignment_id` INT NOT NULL,
  `course_id` INT NULL,
  `points_possible` INT NULL,
  `instances_allowed` SMALLINT(3) NULL,
  PRIMARY KEY (`assignment_id`),
  INDEX `course_id_idx` (`course_id` ASC),
  CONSTRAINT `assignment_course`
    FOREIGN KEY (`course_id`)
    REFERENCES `bbclone`.`Courses` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bbclone`.`Student_Assignments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bbclone`.`Student_Assignments` (
  `student_id` INT NOT NULL,
  `assignment_id` INT NOT NULL,
  `points_earned` INT NULL,
  PRIMARY KEY (`student_id`, `assignment_id`),
  INDEX `assignment_id_idx` (`assignment_id` ASC),
  CONSTRAINT `score_student`
    FOREIGN KEY (`student_id`)
    REFERENCES `bbclone`.`Students` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `score_assignment`
    FOREIGN KEY (`assignment_id`)
    REFERENCES `bbclone`.`Assignments` (`assignment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bbclone`.`Announcements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bbclone`.`Announcements` (
  `announcement_id` INT NOT NULL,
  `course_id` INT NULL,
  `expiry_date` DATE NULL,
  PRIMARY KEY (`announcement_id`),
  INDEX `course_id_idx` (`course_id` ASC),
  CONSTRAINT `announcement_course`
    FOREIGN KEY (`course_id`)
    REFERENCES `bbclone`.`Courses` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
